env:
        - CF_VERSION=3.7.2

install:
        - wget https://cfengine-package-repos.s3.amazonaws.com/community_binaries/cfengine-community_$CF_VERSION-1_amd64.deb
        - sudo dpkg -i cfengine-community_$CF_VERSION-1_amd64.deb

script:
        - cd $TRAVIS_BUILD_DIR && make check
