# SPDX-License-Identifier: CC-BY-SA-2.0
# SPDX-FileCopyrightText: 2013-2020 Normation SAS
openapi: 3.1.0
info:
  title: Rudder API
  version: "22"
  # Will be substituted by content of the file at build
  description: "introduction.md"
  x-logo:
    url: "assets/rudder-logo-rect-black.svg"
  contact:
    email: dev@rudder.io
    name: Rudder developers
    url: "https://www.rudder.io"
  license:
    name: "CC-BY-SA 2.0"
    url: "https://spdx.org/licenses/CC-BY-SA-2.0.html"
servers:
  - url: https://{rudderServer}/rudder/api/latest
    description: "Rudder server"
    variables:
      rudderServer:
        default: rudder.example.com
        description: Hostname of the Rudder server
components:
  securitySchemes:
    $ref: components/securitySchemes/token.yml
security:
  # Apply the same auth everywhere by default, can be overridden
  - "API-Tokens": []
tags:
  - name: API Info
    description: Information about API endpoints and versions
  - name: Status
    description: Is alive check
  - name: Compliance
    description: Access compliance data
  - name: Rules
    description: Rules management
  - name: Directives
    description: Directives management
  - name: Techniques
    description: Techniques management
  - name: Groups
    description: Groups management
  - name: Nodes
    description: Nodes management
  - name: Inventories
    description: Inventory processing service
  - name: Parameters
    description: Global properties
  - name: Campaigns
    description: Campaigns
  - name: Archives
    description: Import and export zip of policies
  - name: Settings
    description: Server configuration
  - name: System
    description: Internal components and administration
  - name: User management
    description: Manage user information and configuration file
  - name: API account management
    description: Manage API accounts
  - name: Plugins
    description: Information about installed plugins
  - name: "ðŸ§© Change requests"
    description: >-
      **Requires that the `changes-validation` plugin is installed on the server.**


      Manage change requests.
  - name: "ðŸ§© CVE"
    description: >-
      **Requires that the `cve` plugin is installed on the server.**


      Manage CVE plugins data and configuration.
  - name: "ðŸ§© System update campaigns"
    description: >-
      **Requires that the `system update` plugin is installed on the server.**


      Fetch System update campaigns results.
  - name: "ðŸ§© Data sources"
    description: >-
      **Requires that the `datasources` plugin is installed on the server.**


      Data sources plugin configuration.
  - name: "ðŸ§© Scale out Relay"
    description: >-
      **Requires that the `scale-out-relay` plugin is installed on the server.**


      Manage relays.
  - name: "ðŸ§© Branding"
    description: >-
      **Requires that the `branding` plugin is installed on the server.**


      Manage web interface customization.
  - name: "ðŸ§© Secret management"
    description: >-
      **Requires that the `secret-management` plugin is installed on the server.**


      Manage secrets variables.
  - name: "ðŸ§© OpenSCAP"
    description: >-
      **Requires that the `openscap` plugin is installed on the server.**


      Get OpenSCAP reports for nodes.
  - name: "ðŸ§© Multi-tenants"
    description: >-
      **Requires that the `multitenants` plugin is installed on the server.**


      Manage tenants and set them on nodes.
paths:
  "/info":
    $ref: paths/info/all.yml
  "/info/{sectionId}":
    $ref: paths/info/section-id.yml
  "/info/details/{endpointName}":
    $ref: paths/info/endpoint-id.yml
  "/status":
    $ref: paths/unauthenticated/status.yml
  "/usermanagement/users":
    $ref: paths/usermanagement/all.yml
  "/usermanagement/{username}":
    $ref: paths/usermanagement/id.yml
  "/usermanagement/update/{username}":
    $ref: paths/usermanagement/update.yml
  "/usermanagement/update/info/{username}":
    $ref: paths/usermanagement/update-info.yml
  "/usermanagement/roles":
    $ref: paths/usermanagement/roles.yml
  "/usermanagement/users/reload":
    $ref: paths/usermanagement/reload.yml
  "/usermanagement":
    $ref: paths/usermanagement/add.yml
  "/usermanagement/status/activate/{username}":
    $ref: paths/usermanagement/activate.yml
  "/usermanagement/status/disable/{username}":
    $ref: paths/usermanagement/disable.yml
  "/usermanagement/coverage/{username}":
    $ref: paths/usermanagement/coverage.yml
  "/apiaccounts":
    $ref: paths/api-accounts/all.yml
  "/apiaccounts/${apiAccountId}":
    $ref: paths/api-accounts/id.yml
  "/apiaccounts/${apiAccountId}/regenerate":
    $ref: paths/api-accounts/regenerate-token.yml
  "/scaleoutrelay/promote/{nodeId}":
    $ref: paths/scale-out-relay/promote.yml
  "/scaleoutrelay/demote/{nodeId}":
    $ref: paths/scale-out-relay/demote.yml
  "/changeRequests/{changeRequestId}/accept":
    $ref: paths/change-requests/accept.yml
  "/changeRequests/{changeRequestId}":
    $ref: paths/change-requests/id.yml
  "/api/changeRequests":
    $ref: paths/change-requests/all.yml
  "/users":
    $ref: paths/change-requests/valid-users.yml
  "/validatedUsers/{username}":
    $ref: paths/change-requests/remove-valid-users.yml
  "/validatedUsers":
    $ref: paths/change-requests/update-valid-users.yml
  "/compliance":
    $ref: paths/compliance/global.yml
  "/compliance/rules":
    $ref: paths/compliance/rules.yml
  "/compliance/rules/{ruleId}":
    $ref: paths/compliance/rule.yml
  "/compliance/directives/{directiveId}":
    $ref: paths/compliance/directive.yml
  "/compliance/directives":
    $ref: paths/compliance/directives.yml
  "/compliance/nodes":
    $ref: paths/compliance/nodes.yml
  "/compliance/nodes/{nodeId}":
    $ref: paths/compliance/node.yml
  "/compliance/groups/{targetOrNodeGroupId}":
    $ref: paths/compliance/group-global.yml
  "/compliance/groups/{targetOrNodeGroupId}/target":
    $ref: paths/compliance/group-targeted.yml
  "/archives/export":
    $ref: paths/archives/export.yml
  "/archives/import":
    $ref: paths/archives/import.yml
  "/system/status":
    $ref: paths/system/status.yml
  "/system/info":
    $ref: paths/system/info.yml
  "/system/reload":
    $ref: paths/system/reload.yml
  "/system/reload/techniques":
    $ref: paths/system/reload-techniques.yml
  "/system/reload/groups":
    $ref: paths/system/reload-groups.yml
  "/system/regenerate/policies":
    $ref: paths/system/regenerate-policies.yml
  "/system/update/policies":
    $ref: paths/system/update-policies.yml
  "/system/archives/{archiveKind}":
    $ref: paths/system/archives.yml
  "/system/archives/{archiveKind}/restore/{archiveRestoreKind}":
    $ref: paths/system/archives-restore.yml
  "/system/archives/{archiveKind}/zip/{commitId}":
    $ref: paths/system/archives-zip.yml
  "/system/healthcheck":
    $ref: paths/system/healthcheck.yml
  "/system/maintenance/purgeSoftware":
    $ref: paths/system/purge-software.yml
  "/plugins/info":
    $ref: paths/plugins/info.yml
  "/plugins/settings":
    $ref: paths/plugins/settings.yml
  "/settings":
    $ref: paths/settings/list.yml
  "/settings/{settingId}":
    $ref: paths/settings/setting.yml
  "/settings/allowed_networks/{nodeId}":
    $ref: paths/settings/allowed_networks.yml
  "/settings/allowed_networks/{nodeId}/diff":
    $ref: paths/settings/allowed_networks_diff.yml
  "/parameters":
    $ref: paths/parameters/parameters.yml
  "/parameters/{parameterId}":
    $ref: paths/parameters/parameters-id.yml
  "/inventories/upload":
    $ref: paths/inventories/upload.yml
  "/inventories/watcher/start":
    $ref: paths/inventories/start.yml
  "/inventories/watcher/stop":
    $ref: paths/inventories/stop.yml
  "/inventories/watcher/restart":
    $ref: paths/inventories/restart.yml
  "/datasources":
    $ref: paths/datasources/all.yml
  "/datasources/{datasourceId}":
    $ref: paths/datasources/id.yml
  "/datasources/reload":
    $ref: paths/datasources/reload.yml
  "/datasources/reload/{datasourceId}":
    $ref: paths/datasources/reload-id.yml
  "/nodes/{nodeId}/fetchData":
    $ref: paths/datasources/reload-node.yml
  "/nodes/{nodeId}/fetchData/{datasourceId}":
    $ref: paths/datasources/reload-node-id.yml
  "/nodes":
    $ref: paths/nodes/all.yml
  "/nodes/applyPolicy":
    $ref: paths/nodes/apply-policy.yml
  "/nodes/status":
    $ref: paths/nodes/status.yml
  "/nodes/pending":
    get:
      $ref: paths/nodes/pending-all.yml
    post:
      $ref: paths/nodes/pending-update.yml
  "/nodes/{nodeId}":
    $ref: paths/nodes/id.yml
  "/nodes/pending/{nodeId}":
    $ref: paths/nodes/pending-id.yml
  "/nodes/{nodeId}/inheritedProperties":
    $ref: paths/nodes/inherited-properties.yml
  "/nodes/{nodeId}/applyPolicy":
    $ref: paths/nodes/apply-policy-id.yml
  "/techniques":
    $ref: paths/techniques/all.yml
  "/techniques/{techniqueId}/directives":
    $ref: paths/techniques/name.yml
  "/techniques/{techniqueId}/{techniqueVersion}/directives":
    $ref: paths/techniques/name-version.yml
  "/techniques/reload":
    $ref: paths/techniques/reload-technique.yml
  "/techniques/categories":
    $ref: paths/techniques/categories.yml
  "/techniques/versions":
    $ref: paths/techniques/versions.yml
  "/techniques/{techniqueId}/{techniqueVersion}/revisions":
    $ref: paths/techniques/revisions.yml
  "/techniques/{techniqueId}/{techniqueVersion}/resources":
    $ref: paths/techniques/resources.yml
  "/techniques/{techniqueId}":
    $ref: paths/techniques/id.yml
  "/techniques/{techniqueId}/{techniqueVersion}":
    $ref: paths/techniques/id-version.yml
  "/methods":
    $ref: paths/techniques/all-methods.yml
  "/methods/reload":
    $ref: paths/techniques/methods-reload.yml
  "/groups":
    $ref: paths/groups/all.yml
  "/groups/{groupId}":
    $ref: paths/groups/id.yml
  "/groups/{groupId}/reload":
    $ref: paths/groups/reload.yml
  "/groups/categories/{groupCategoryId}":
    $ref: paths/groups/category-id.yml
  "/groups/categories":
    $ref: paths/groups/categories.yml
  "/groups/tree":
    $ref: paths/groups/tree.yml
  "/directives":
    $ref: paths/directives/all.yml
  "/directives/{directiveId}":
    $ref: paths/directives/id.yml
  "/directives/{directiveId}/check":
    $ref: paths/directives/id-check.yml
  "/directives/tree":
    $ref: paths/directives/tree.yml
  "/rules":
    $ref: paths/rules/all.yml
  "/rules/{ruleId}":
    $ref: paths/rules/id.yml
  "/rules/categories":
    $ref: paths/rules/categories.yml
  "/rules/categories/{ruleCategoryId}":
    $ref: paths/rules/category-id.yml
  "/rules/tree":
    $ref: paths/rules/tree.yml
  "/branding":
    $ref: paths/branding/conf.yml
  "/branding/reload":
    $ref: paths/branding/reload.yml
  "/cve/check/last":
    $ref: paths/cve/last.yml
  "/cve/check":
    $ref: paths/cve/check.yml
  "/cve/check/config":
    $ref: paths/cve/checkConfig.yml
  "/cve":
    $ref: paths/cve/allCVE.yml
  "/cve/{cveId}":
    $ref: paths/cve/getCVE.yml
  "/cve/list":
    $ref: paths/cve/listCVE.yml
  "/cve/update/fs":
    $ref: paths/cve/updateCVEFromFS.yml
  "/cve/update":
    $ref: paths/cve/updateCVE.yml
  "/secret":
    $ref: paths/secret/all.yml
  "/secret/{name}":
    $ref: paths/secret/id.yml
  "/campaigns":
    $ref: paths/campaigns/allCampaigns.yml
  "/campaigns/{id}":
    $ref: paths/campaigns/getCampaign.yml
  "/campaigns/events":
    $ref: paths/campaigns/allEvents.yml
  "/campaigns/events/{id}":
    $ref: paths/campaigns/getEvent.yml
  "/campaigns/{id}/events":
    $ref: paths/campaigns/getEventsCampaign.yml
  "/campaigns/{id}/schedule":
    $ref: paths/campaigns/scheduleCampaign.yml
  "/systemUpdate/events/{id}/result/{nodeId}":
    $ref: paths/systemUpdate/detailedResult.yml
  "/systemUpdate/events/{id}/result":
    $ref: paths/systemUpdate/eventResult.yml
  "/systemUpdate/events/{id}/report":
    $ref: paths/systemUpdate/report.yml
  "/systemUpdate/events/{id}/summaryReport":
    $ref: paths/systemUpdate/summaryReport.yml
  "/systemUpdate/campaign/{id}/history":
    $ref: paths/systemUpdate/campaignHistory.yml
  "/openscap/report/{nodeId}":
    $ref: paths/openscap/report.yml
  "/tenants":
    $ref: paths/tenants/all.yml
  "/tenants/{id}":
    $ref: paths/tenants/id.yml
  "/securitytags/nodes":
    $ref: paths/securitytags/nodes.yml
