# SPDX-License-Identifier: CC-BY-SA-2.0
# SPDX-FileCopyrightText: 2013-2020 Normation SAS
openapi: 3.0.3
info:
  title: Rudder relay API
  version: "1"
  description: introduction.yml
  x-logo:
    url: "assets/rudder.svg"
  contact:
    email: dev@rudder.io
    name: Rudder developers
    url: "https://www.rudder.io"
  license:
    name: "CC-BY-SA 2.0"
    url: "https://spdx.org/licenses/CC-BY-SA-2.0.html"
servers:
  - url: "http://localhost:3030"
    description: "Local API"
externalDocs:
  description: Learn more about Rudder.
  url: "https://docs.rudder.io"
tags:
  - name: System
    description: Internal relay service management
  - name: Policies
    description: Policies distributed by the relay
  - name: Shared folder
    description: Distribute file from the shared folder
  - name: Shared files
    description: Share files between nodes
  - name: Remote run
    description: Trigger agents runs
paths:
  "/rudder/relay-api/1/system/status":
    $ref: paths/system/status.yml
  "/rudder/relay-api/1/system/info":
    $ref: paths/system/info.yml
  "/rudder/relay-api/1/system/reload":
    $ref: paths/system/reload.yml
  "/rudder/relay-api/1/shared-folder/{path}":
    $ref: paths/shared-folder.yml
  "/rudder/relay-api/1/shared-files/{targetNodeId}/{sourceNodeId}/{fileId}":
    $ref: paths/shared-files.yml
  "/rudder/relay-api/1/policies/{nodeId}/rules/dsc/rudder.zip":
    $ref: paths/policies.yml
  "/rudder/relay-api/1/remote-run/nodes/{nodeId}":
    $ref: paths/remote-run/node.yml
  "/rudder/relay-api/1/remote-run/nodes":
    $ref: paths/remote-run/nodes.yml
  "/rudder/relay-api/1/remote-run/all":
    $ref: paths/remote-run/all.yml
  "/metrics":
    $ref: paths/metrics.yml
